### PR TITLE
Create the database

### PR DESCRIPTION
**Pull request by TolikPylypchuk**
The main task here is to create the infrastructure for creating the database. As it turns out, SQLite is supported natively in Android.

### CODE REVIEW

**Comment by TolikPylypchuk** [comment]
I may have overestimated the task. Adding Sugar ORM made this one really easy, because it does all the heavy lifting, such as creating, updating or opening the database.

All I need to do now is to create the actual entity classes. We don't need schema.sql anymore as Sugar ORM creates one itself from the entity classes.

**Comment by TolikPylypchuk** [comment]
One quirk about Sugar ORM is that you must disable Instant Run for it to work (at least for the first run of an app on a device). You can disable it in Settings > Build, Execution, Deployment > Instant Run

If you have already made the grave mistake of running the app with Instant Run turned on, you must uninstall the app manually, diasble Instant Run, and then run it again.

**Comment by YaroslavKormushyn** [comment]
It builds and runs on my device (Marshmallow 5.0.2).
Entities are okay to me.
Where is the default SQLite .db file located?

**Comment by TolikPylypchuk** [comment]
I have absolutely no idea.

**Review by YaroslavKormushyn — APPROVED** [review]

**Pull request merged**
